### ISSUE TITLE
`clearOnSelect` prop seems broken

### ISSUE THREAD

**Issue by pl4nty** [ghoshnirmalya/react-search-box#153]
I'm not super familiar with hooks but this seems pretty broken?

https://github.com/ghoshnirmalya/react-search-box/blob/70bbb68dcbc2a08423816c1b42d25993d1dca04e/src/index.tsx#L176-L181

**Comment by ghoshnirmalya** [comment]
Fixed in [2.1.2](https://github.com/ghoshnirmalya/react-search-box/releases/tag/v2.1.2).
