### ISSUE TITLE
Adding a name prop 

### ISSUE THREAD

**Issue by MuhammadGb** [ghoshnirmalya/react-search-box#159]
Would it be possible to add a name prop to the component. Some like me are finding it hard to submit when wrapped around the Formik library

**Comment by ghoshnirmalya** [comment]
Thank you for the feedback. It should be easy to do that. You can add the `name` prop [here](https://github.com/ghoshnirmalya/react-search-box/blob/master/src/index.tsx#L97-L114) and pass it to the `InputBox` component [here](https://github.com/ghoshnirmalya/react-search-box/blob/master/src/index.tsx#L212-L224).

Then, in the `InputBox` component, you can simply use that prop [here](https://github.com/ghoshnirmalya/react-search-box/blob/master/src/input/index.tsx#L62-L76).

Would you like to create a PR for the same?

**Comment by MuhammadGb** [comment]
Yes, definitely, I can do so.

**Comment by ghoshnirmalya** [comment]
@MuhammadGb That's great to hear. What access do you need? You can create a PR from your fork.

**Comment by MuhammadGb** [comment]
@ghoshnirmalya Thanks. I got it now. I will make the PR from my fork.
