### ISSUE TITLE
BUG on React v18.2.0

### ISSUE THREAD

**Issue by binmulindi6** [ghoshnirmalya/react-search-box#167]
it's not working
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

**Comment by petrkucerak** [comment]
I have the same problem as @binmulindi6. Your plugin is incompatible with React 18. Will you @ghoshnirmalya solve this problem in the future?

**Comment by ghoshnirmalya** [comment]
[Fixed in 3.0.0](https://github.com/ghoshnirmalya/react-search-box/releases/tag/v3.0.0).
