### ISSUE TITLE
Case sensitivity of search terms

### ISSUE THREAD

**Issue by jpmasud** [ghoshnirmalya/react-search-box#2]
Hi there, just wondering if there's any way to make the search case-insensitive?

**Comment by MarkusJ13** [comment]
You can convert the data to lower case :D

**Comment by jpmasud** [comment]
But that means the end-user will see lower-case data as well :(

**Comment by ghoshnirmalya** [comment]
@ashok10103 May be you can create a PR to this repository with that as an enhancement?

**Comment by ghoshnirmalya** [comment]
Fixed in https://github.com/ghoshnirmalya/react-search-box/releases/tag/v1.0.2.
