### ISSUE TITLE
I cant seem to update the data value after I render the ReactSearchBox

### ISSUE THREAD

**Issue by shadowae** [ghoshnirmalya/react-search-box#40]
I use a container to a page to get the suggested value from the redux store and pass it to the page props and to the ReactSearchBox. When i type the store value gets up dated and so does the page props. But the ReactSearchBox does not show the suggested values

**Comment by ghoshnirmalya** [comment]
@shadowae Thank you for reporting this issue. Which version of react-search-box are you using?

**Comment by shadowae** [comment]
Hi.

I'm using the latest as of two days back.

Thanks and Regards,
Satish Kumar

**Comment by ghoshnirmalya** [comment]
@shadowae Did you mean that when you're updating the `data` prop, React Search Box is not updating the dropdown that appears? If so, can you please share an example?

I checked and it seemed to work due to https://github.com/ghoshnirmalya/react-search-box/blob/master/src/index.js#L137-L144.
